[2024-06-04T07:03:05.662+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:05.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:03:05.665+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:03:05.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:05.698+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:03:05.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:03:05.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:05.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-06-04T07:03:36.353+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:36.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:03:36.358+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:03:36.358+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:36.383+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:03:36.378+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:03:36.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:03:36.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.071 seconds
[2024-06-04T07:04:06.728+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:06.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:04:06.738+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:04:06.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:06.835+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:04:06.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:04:06.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:06.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.214 seconds
[2024-06-04T07:04:37.291+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:37.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:04:37.303+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:04:37.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:37.406+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:04:37.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:04:37.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:04:37.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.216 seconds
[2024-06-04T07:05:07.730+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:07.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:05:07.732+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:05:07.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:07.752+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:05:07.747+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:05:07.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:07.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-06-04T07:05:38.004+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:38.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:05:38.010+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:05:38.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:38.080+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:05:38.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:05:38.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:05:38.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.125 seconds
[2024-06-04T07:06:08.217+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:08.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:06:08.220+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:06:08.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:08.239+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:06:08.235+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:06:08.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:08.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-06-04T07:06:38.520+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:38.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:06:38.534+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:06:38.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:38.633+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:06:38.606+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:06:38.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:06:38.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.245 seconds
[2024-06-04T07:07:09.074+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:09.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:07:09.081+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:07:09.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:09.111+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:07:09.104+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:07:09.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:09.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.077 seconds
[2024-06-04T07:07:39.374+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:39.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:07:39.386+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:07:39.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:39.494+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:07:39.465+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:07:39.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:07:39.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.246 seconds
[2024-06-04T07:08:09.698+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:09.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:08:09.702+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:08:09.702+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:09.726+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:08:09.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:08:09.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:09.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-06-04T07:08:40.017+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:40.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:08:40.028+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:08:40.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:40.135+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:08:40.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:08:40.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:08:40.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.231 seconds
[2024-06-04T07:09:10.448+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:10.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:09:10.451+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:09:10.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:10.477+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:09:10.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:09:10.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:10.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-06-04T07:09:40.677+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:40.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:09:40.679+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:09:40.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:40.698+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:09:40.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:09:40.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:09:40.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-06-04T07:10:11.121+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:11.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:10:11.132+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:10:11.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:11.227+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:10:11.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:10:11.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:11.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.159 seconds
[2024-06-04T07:10:41.305+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:41.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:10:41.309+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:10:41.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:41.333+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:10:41.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:10:41.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:10:41.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2024-06-04T07:11:11.498+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:11.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:11:11.500+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:11:11.500+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:11.519+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:11:11.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:11:11.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:11.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-06-04T07:11:41.909+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:41.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:11:41.918+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:11:41.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:42.022+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:11:41.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:11:42.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:11:42.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.208 seconds
[2024-06-04T07:12:12.373+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:12.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:12:12.376+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:12:12.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:12.393+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:12:12.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:12:12.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:12.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-06-04T07:12:42.580+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:42.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:12:42.582+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:12:42.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:42.604+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:12:42.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:12:42.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:12:42.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-06-04T07:13:12.874+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:12.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:13:12.877+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:13:12.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:12.901+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:13:12.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:13:12.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:12.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-06-04T07:13:43.150+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:43.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:13:43.152+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:13:43.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:43.169+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:13:43.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:13:43.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:13:43.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-06-04T07:14:13.406+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:13.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:14:13.408+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:14:13.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:13.426+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:14:13.421+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:14:13.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:13.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-06-04T07:14:43.673+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:43.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:14:43.677+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:14:43.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:43.703+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:14:43.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:14:43.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:14:43.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-06-04T07:15:13.930+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:13.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:15:13.936+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:15:13.934+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:13.953+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:15:13.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:15:13.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:13.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-06-04T07:15:44.210+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:44.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:15:44.213+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:15:44.212+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:44.232+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:15:44.228+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:15:44.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:15:44.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-06-04T07:16:14.455+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:14.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:16:14.458+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:16:14.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:14.479+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:16:14.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:16:14.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:14.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-06-04T07:16:44.803+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:44.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:16:44.805+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:16:44.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:44.820+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:16:44.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:16:44.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:16:44.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-06-04T07:17:15.013+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:15.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:17:15.015+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:17:15.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:15.031+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:17:15.027+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:17:15.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:15.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-06-04T07:17:45.374+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:45.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:17:45.379+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:17:45.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:45.410+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:17:45.405+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:17:45.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:17:45.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-06-04T07:18:15.745+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T07:18:15.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T07:18:15.753+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:18:15.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T07:18:15.789+0000] {logging_mixin.py:188} INFO - [2024-06-04T07:18:15.786+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T07:18:15.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T07:18:15.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2024-06-04T09:09:09.269+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:09.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:09:09.273+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:09:09.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:09.299+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:09:09.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:09:09.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:09.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-06-04T09:09:39.630+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:39.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:09:39.635+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:09:39.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:39.671+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:09:39.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:09:39.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:09:39.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2024-06-04T09:10:09.790+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:09.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:10:09.793+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:10:09.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:09.818+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:10:09.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:10:09.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:09.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-06-04T09:10:40.068+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:40.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:10:40.072+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:10:40.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:40.101+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:10:40.093+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:10:40.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:10:40.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.073 seconds
[2024-06-04T09:11:10.285+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:10.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:11:10.287+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:11:10.287+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:10.312+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:11:10.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:11:10.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:10.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2024-06-04T09:11:40.575+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:40.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:11:40.578+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:11:40.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:40.612+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:11:40.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:11:40.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:11:40.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-06-04T09:12:10.795+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:10.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:12:10.799+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:12:10.798+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:10.822+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:12:10.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:12:10.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:10.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-06-04T09:12:41.056+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:41.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:12:41.059+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:12:41.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:41.093+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:12:41.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:12:41.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:12:41.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.070 seconds
[2024-06-04T09:13:11.261+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:11.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:13:11.264+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:13:11.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:11.289+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:13:11.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:13:11.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:11.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2024-06-04T09:13:41.520+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:41.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:13:41.527+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:13:41.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:41.577+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:13:41.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:13:41.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:13:41.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
[2024-06-04T09:14:11.752+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:11.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:14:11.757+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:14:11.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:11.786+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:14:11.777+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:14:11.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:11.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-06-04T09:14:42.017+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:42.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:14:42.022+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:14:42.020+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:42.075+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:14:42.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:14:42.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:14:42.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.100 seconds
[2024-06-04T09:15:12.177+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:12.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:15:12.181+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:15:12.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:12.203+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:15:12.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:15:12.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:12.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2024-06-04T09:15:42.356+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:42.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:15:42.359+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:15:42.359+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:42.386+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:15:42.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:15:42.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:15:42.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2024-06-04T09:16:12.566+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:12.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:16:12.570+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:16:12.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:12.595+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:16:12.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:16:12.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:12.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-06-04T09:16:42.735+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:42.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:16:42.738+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:16:42.738+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:42.759+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:16:42.754+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:16:42.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:16:42.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-06-04T09:17:12.980+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:12.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:17:12.983+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:17:12.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:13.004+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:17:12.998+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:17:13.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:13.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-06-04T09:17:43.333+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:43.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:17:43.344+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:17:43.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:43.447+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:17:43.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:17:43.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:17:43.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.211 seconds
[2024-06-04T09:18:13.788+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:13.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:18:13.791+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:18:13.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:13.815+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:18:13.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:18:13.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:13.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-06-04T09:18:44.147+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:44.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:18:44.156+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:18:44.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:44.252+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:18:44.226+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:18:44.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:18:44.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.205 seconds
[2024-06-04T09:19:14.418+0000] {processor.py:161} INFO - Started process (PID=395) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:14.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:19:14.421+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:19:14.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:14.441+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:19:14.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:19:14.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:14.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-06-04T09:19:44.800+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:44.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:19:44.810+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:19:44.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:44.911+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:19:44.882+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:19:44.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:19:44.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.217 seconds
[2024-06-04T09:20:15.272+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:15.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:20:15.276+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:20:15.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:15.302+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:20:15.296+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:20:15.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:15.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-06-04T09:20:45.494+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:45.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:20:45.512+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:20:45.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:45.576+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:20:45.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:20:45.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:20:45.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.131 seconds
[2024-06-04T09:21:15.755+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:15.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:21:15.759+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:21:15.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:15.793+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:21:15.784+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:21:15.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:15.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2024-06-04T09:21:46.052+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:46.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:21:46.058+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:21:46.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:46.106+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:21:46.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:21:46.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:21:46.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.097 seconds
[2024-06-04T09:22:16.362+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/test_dag.py
[2024-06-04T09:22:16.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-06-04T09:22:16.366+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:22:16.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-06-04T09:22:16.408+0000] {logging_mixin.py:188} INFO - [2024-06-04T09:22:16.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-04T09:22:16.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-06-04T09:22:16.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
