[2024-05-10T02:01:21.876+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:21.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:01:21.883+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:01:21.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:21.925+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:01:21.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:01:21.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:21.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-05-10T02:01:52.345+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:52.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:01:52.360+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:01:52.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:52.395+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:01:52.388+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:01:52.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:01:52.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.129 seconds
[2024-05-10T02:02:22.503+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:22.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:02:22.506+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:02:22.506+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:22.523+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:02:22.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:02:22.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:22.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-10T02:02:52.660+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:52.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:02:52.664+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:02:52.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:52.680+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:02:52.675+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:02:52.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:02:52.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
[2024-05-10T02:03:22.842+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:03:22.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:03:22.846+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:03:22.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:03:22.859+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:03:22.856+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:03:22.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:03:22.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T02:45:24.826+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:24.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:45:24.855+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:45:24.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:24.943+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:45:24.917+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:45:24.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:24.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.259 seconds
[2024-05-10T02:45:55.185+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:55.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:45:55.199+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:45:55.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:55.231+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:45:55.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:45:55.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:45:55.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.105 seconds
[2024-05-10T02:46:25.325+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:25.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:46:25.330+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:46:25.329+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:25.347+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:46:25.343+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:46:25.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:25.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-10T02:46:55.476+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:55.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:46:55.480+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:46:55.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:55.497+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:46:55.493+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:46:55.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:46:55.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-05-10T02:47:25.724+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:25.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:47:25.734+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:47:25.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:25.761+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:47:25.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:47:25.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:25.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.110 seconds
[2024-05-10T02:47:55.898+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:55.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:47:55.902+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:47:55.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:55.920+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:47:55.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:47:55.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:47:55.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-10T02:48:26.151+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:26.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:48:26.154+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:48:26.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:26.179+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:48:26.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:48:26.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:26.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.078 seconds
[2024-05-10T02:48:56.308+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:56.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:48:56.311+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:48:56.311+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:56.329+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:48:56.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:48:56.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:48:56.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-05-10T02:49:26.543+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:26.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:49:26.547+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:49:26.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:26.567+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:49:26.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:49:26.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:26.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-10T02:49:56.693+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:56.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:49:56.696+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:49:56.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:56.715+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:49:56.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:49:56.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:49:56.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-10T02:50:27.019+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:27.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:50:27.023+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:50:27.022+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:27.050+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:50:27.043+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:50:27.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:27.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.099 seconds
[2024-05-10T02:50:57.310+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:57.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:50:57.337+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:50:57.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:57.443+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:50:57.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:50:57.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:50:57.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.235 seconds
[2024-05-10T02:51:27.722+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:27.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:51:27.727+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:51:27.726+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:27.747+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:51:27.741+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:51:27.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:27.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-05-10T02:51:58.203+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:58.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:51:58.236+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:51:58.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:58.332+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:51:58.307+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:51:58.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:51:58.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.459 seconds
[2024-05-10T02:52:29.234+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:52:29.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:52:29.271+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:52:29.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:52:29.338+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:52:29.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:52:29.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:52:29.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.322 seconds
[2024-05-10T02:52:59.987+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:52:59.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:53:00.066+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:53:00.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:53:00.185+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:53:00.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:53:00.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:53:00.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.468 seconds
[2024-05-10T02:53:30.512+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:53:30.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:53:30.519+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:53:30.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:53:30.541+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:53:30.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:53:30.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:53:30.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2024-05-10T02:54:00.687+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:00.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:54:00.696+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:54:00.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:00.718+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:54:00.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:54:00.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:00.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.074 seconds
[2024-05-10T02:54:30.871+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:30.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:54:30.875+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:54:30.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:30.892+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:54:30.888+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:54:30.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:54:30.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-10T02:55:01.053+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:01.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:55:01.056+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:55:01.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:01.073+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:55:01.068+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:55:01.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:01.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-10T02:55:31.287+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:31.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:55:31.291+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:55:31.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:31.330+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:55:31.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:55:31.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:55:31.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2024-05-10T02:56:01.443+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:01.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:56:01.447+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:56:01.446+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:01.465+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:56:01.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:56:01.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:01.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T02:56:31.647+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:31.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:56:31.650+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:56:31.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:31.666+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:56:31.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:56:31.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:56:31.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T02:57:01.808+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:01.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:57:01.811+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:57:01.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:01.826+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:57:01.821+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:57:01.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:01.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-10T02:57:31.974+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:31.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:57:31.977+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:57:31.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:31.993+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:57:31.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:57:31.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:57:32.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T02:58:02.134+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:02.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:58:02.136+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:58:02.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:02.155+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:58:02.149+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:58:02.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:02.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-10T02:58:32.300+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:32.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:58:32.302+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:58:32.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:32.319+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:58:32.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:58:32.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:58:32.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T02:59:02.461+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:02.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:59:02.463+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:59:02.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:02.480+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:59:02.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:59:02.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:02.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T02:59:32.633+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:32.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T02:59:32.636+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:59:32.635+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:32.652+0000] {logging_mixin.py:188} INFO - [2024-05-10T02:59:32.648+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T02:59:32.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T02:59:32.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T03:00:02.794+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:02.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:00:02.798+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:00:02.798+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:02.822+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:00:02.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:00:02.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:02.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-05-10T03:00:33.099+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:33.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:00:33.103+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:00:33.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:33.127+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:00:33.121+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:00:33.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:00:33.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-05-10T03:01:03.244+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:03.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:01:03.248+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:01:03.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:03.266+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:01:03.261+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:01:03.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:03.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-10T03:01:33.436+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:33.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:01:33.438+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:01:33.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:33.455+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:01:33.451+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:01:33.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:01:33.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T03:02:03.604+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:03.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:02:03.607+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:02:03.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:03.627+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:02:03.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:02:03.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:03.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-05-10T03:02:33.777+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:33.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:02:33.780+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:02:33.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:33.798+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:02:33.792+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:02:33.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:02:33.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-10T03:03:03.958+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:03.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:03:03.962+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:03:03.962+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:03.999+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:03:03.980+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:03:04.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:04.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.085 seconds
[2024-05-10T03:03:34.152+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:34.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:03:34.155+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:03:34.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:34.172+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:03:34.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:03:34.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:03:34.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T03:04:04.343+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:04.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:04:04.346+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:04:04.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:04.364+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:04:04.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:04:04.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:04.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-10T03:04:34.512+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:34.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:04:34.514+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:04:34.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:34.532+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:04:34.527+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:04:34.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:04:34.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-05-10T03:05:04.756+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:04.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:05:04.759+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:05:04.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:04.776+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:05:04.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:05:04.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:04.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-10T03:05:34.965+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:34.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:05:34.968+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:05:34.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:34.986+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:05:34.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:05:34.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:05:35.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-10T03:07:03.706+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:03.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:07:03.724+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:07:03.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:03.762+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:07:03.751+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:07:03.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:03.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.166 seconds
[2024-05-10T03:07:34.157+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:34.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:07:34.184+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:07:34.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:34.240+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:07:34.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:07:34.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:07:34.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.212 seconds
[2024-05-10T03:08:04.713+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:04.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:08:04.719+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:08:04.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:04.741+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:08:04.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:08:04.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:04.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.118 seconds
[2024-05-10T03:08:34.945+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:34.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:08:34.951+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:08:34.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:34.971+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:08:34.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:08:34.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:08:34.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-05-10T03:09:05.113+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:05.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:09:05.116+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:09:05.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:05.134+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:09:05.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:09:05.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:05.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-10T03:09:35.299+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:35.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:09:35.303+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:09:35.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:35.320+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:09:35.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:09:35.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:09:35.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-05-10T03:10:05.462+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:05.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:10:05.465+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:10:05.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:05.483+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:10:05.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:10:05.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:05.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-10T03:10:35.654+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:35.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:10:35.658+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:10:35.658+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:35.677+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:10:35.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:10:35.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:10:35.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-10T03:11:05.824+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:05.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:11:05.828+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:11:05.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:05.846+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:11:05.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:11:05.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:05.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T03:11:36.008+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:36.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:11:36.011+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:11:36.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:36.029+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:11:36.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:11:36.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:11:36.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-10T03:12:06.276+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:06.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:12:06.278+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:12:06.278+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:06.294+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:12:06.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:12:06.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:06.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T03:12:36.461+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:36.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:12:36.469+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:12:36.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:36.501+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:12:36.493+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:12:36.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:12:36.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2024-05-10T03:13:06.642+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:06.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:13:06.645+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:13:06.645+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:06.661+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:13:06.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:13:06.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:06.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-10T03:13:36.838+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:36.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:13:36.841+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:13:36.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:36.857+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:13:36.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:13:36.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:13:36.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T03:14:07.009+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:07.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:14:07.011+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:14:07.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:07.027+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:14:07.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:14:07.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:07.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T03:14:37.170+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:37.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:14:37.172+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:14:37.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:37.189+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:14:37.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:14:37.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:14:37.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T03:15:07.351+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:07.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:15:07.353+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:15:07.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:07.367+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:15:07.363+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:15:07.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:07.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-10T03:15:37.555+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:37.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:15:37.562+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:15:37.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:37.605+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:15:37.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:15:37.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:15:37.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.111 seconds
[2024-05-10T03:16:07.712+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:07.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:16:07.715+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:16:07.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:07.735+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:16:07.730+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:16:07.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:07.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-05-10T03:16:37.867+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:37.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:16:37.871+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:16:37.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:37.890+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:16:37.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:16:37.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:16:37.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-05-10T03:17:08.100+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:08.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:17:08.103+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:17:08.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:08.119+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:17:08.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:17:08.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:08.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-10T03:17:38.999+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:39.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:17:39.004+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:17:39.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:39.021+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:17:39.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:17:39.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:17:39.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T03:18:09.180+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:09.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:18:09.185+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:18:09.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:09.223+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:18:09.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:18:09.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:09.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.073 seconds
[2024-05-10T03:18:39.355+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:39.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:18:39.358+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:18:39.358+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:39.376+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:18:39.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:18:39.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:18:39.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T03:19:09.532+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:09.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:19:09.535+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:19:09.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:09.552+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:19:09.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:19:09.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:09.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-10T03:19:39.692+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:39.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:19:39.694+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:19:39.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:39.712+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:19:39.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:19:39.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:19:39.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-10T03:20:09.872+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:09.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:20:09.875+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:20:09.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:09.891+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:20:09.887+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:20:09.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:09.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-10T03:20:40.031+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:40.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:20:40.035+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:20:40.035+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:40.058+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:20:40.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:20:40.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:20:40.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.065 seconds
[2024-05-10T03:21:10.216+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:10.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:21:10.219+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:21:10.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:10.235+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:21:10.231+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:21:10.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:10.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-10T03:21:40.390+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:40.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:21:40.393+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:21:40.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:40.411+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:21:40.406+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:21:40.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:21:40.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-10T03:22:10.610+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/test_dag.py
[2024-05-10T03:22:10.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-10T03:22:10.613+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:22:10.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-10T03:22:10.631+0000] {logging_mixin.py:188} INFO - [2024-05-10T03:22:10.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-10T03:22:10.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-10T03:22:10.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
