[2024-05-08T07:40:32.177+0000] {processor.py:161} INFO - Started process (PID=6912) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:40:32.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:40:32.179+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:40:32.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:40:32.203+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:40:32.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:40:32.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:40:32.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.054 seconds
[2024-05-08T07:41:02.393+0000] {processor.py:161} INFO - Started process (PID=6971) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:02.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:41:02.395+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:41:02.395+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:02.416+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:41:02.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:41:02.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:02.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.056 seconds
[2024-05-08T07:41:32.561+0000] {processor.py:161} INFO - Started process (PID=7030) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:32.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:41:32.564+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:41:32.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:32.580+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:41:32.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:41:32.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:41:32.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.043 seconds
[2024-05-08T07:42:02.704+0000] {processor.py:161} INFO - Started process (PID=7086) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:02.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:42:02.706+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:42:02.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:02.726+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:42:02.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:42:02.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:02.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.062 seconds
[2024-05-08T07:42:32.847+0000] {processor.py:161} INFO - Started process (PID=7145) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:32.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:42:32.848+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:42:32.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:32.863+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:42:32.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:42:32.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:42:32.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.042 seconds
[2024-05-08T07:43:02.990+0000] {processor.py:161} INFO - Started process (PID=7204) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:02.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:43:02.992+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:43:02.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:03.006+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:43:03.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:43:03.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:03.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.042 seconds
[2024-05-08T07:43:33.325+0000] {processor.py:161} INFO - Started process (PID=7263) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:33.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:43:33.327+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:43:33.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:33.343+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:43:33.337+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:43:33.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:43:33.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.042 seconds
[2024-05-08T07:44:03.676+0000] {processor.py:161} INFO - Started process (PID=7322) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:03.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:44:03.679+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:44:03.678+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:03.696+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:44:03.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:44:03.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:03.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.049 seconds
[2024-05-08T07:44:33.857+0000] {processor.py:161} INFO - Started process (PID=7381) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:33.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:44:33.859+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:44:33.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:33.874+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:44:33.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:44:33.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:44:33.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.042 seconds
[2024-05-08T07:45:04.747+0000] {processor.py:161} INFO - Started process (PID=7438) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:04.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:45:04.748+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:45:04.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:04.767+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:45:04.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:45:04.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:04.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.054 seconds
[2024-05-08T07:45:35.080+0000] {processor.py:161} INFO - Started process (PID=7497) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:35.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:45:35.082+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:45:35.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:35.097+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:45:35.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:45:35.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:45:35.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.042 seconds
[2024-05-08T07:46:05.332+0000] {processor.py:161} INFO - Started process (PID=7556) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:05.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:46:05.335+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:46:05.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:05.354+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:46:05.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:46:05.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:05.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.053 seconds
[2024-05-08T07:46:35.828+0000] {processor.py:161} INFO - Started process (PID=7615) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:35.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:46:35.830+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:46:35.829+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:35.847+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:46:35.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:46:35.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:46:35.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.053 seconds
[2024-05-08T07:47:06.194+0000] {processor.py:161} INFO - Started process (PID=7674) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:47:06.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:47:06.197+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:47:06.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:47:06.214+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:47:06.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:47:06.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:47:06.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.048 seconds
[2024-05-08T07:48:29.023+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:29.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:48:29.055+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:48:29.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:29.094+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:48:29.075+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:48:29.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:29.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.274 seconds
[2024-05-08T07:48:59.851+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:59.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/test_dag.py for tasks to queue
[2024-05-08T07:48:59.856+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:48:59.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:59.876+0000] {logging_mixin.py:188} INFO - [2024-05-08T07:48:59.868+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/__pycache__/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/test_dag.py", line 3, in <module>
    from airflow.operators import FileSensor, BashOperator, PythonOperator, PostgresOperator, EmailOperator
ImportError: cannot import name 'FileSensor' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-05-08T07:48:59.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/test_dag.py
[2024-05-08T07:48:59.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/test_dag.py took 0.065 seconds
